# docker-compose.yml
services:
  web:
    build: .
    volumes:
      - .:/app
    ports:
      - 8000:8000
      - 3300:3300
    depends_on:
      - db
    env_file:
      - .env
  db:
    image: postgres:14
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env

volumes:
  postgres_data: